apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangoapp
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: djangoapp
  template:
    metadata:
      labels:
        app: djangoapp
    spec:
      imagePullSecrets:
        - name: registry-auth
      containers:
        - name: djangoapp
          image: 192.168.0.126:30500/djangoapp:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
